"""Read-only Excel integration for the Rehab Center workbook."""

from .layout_contract import (
    MASTER_SCHEDULE_HEADERS,
    THERAPIST_DAILY_GRID_RANGES,
    THERAPIST_DAILY_HEADER_RANGES,
    WRITE_ZONES,
    CellRange,
    LayoutAudit,
    LayoutIssue,
    LayoutSafetyError,
    assert_cell_write_allowed,
    audit_layout,
    resolve_master_schedule_rows,
    resolve_therapist_daily_cell,
)
from .package_probe import SheetPackageInfo, WorkbookPackageProbe
from .reader import (
    AuditIssue,
    WorkbookAudit,
    WorkbookSettings,
    audit_workbook,
    read_base_schedule,
    read_patients,
    read_settings,
)
from .snapshot import SourceContractError, WorkbookSnapshot, build_snapshot
from .writeback import (
    CellPatch,
    DryRunReport,
    WriteIntent,
    WritePlan,
    WritebackSafetyError,
    TextRunPatch,
    build_write_plan,
    dry_run_writeback,
    validate_write_plan,
)

from .render_plan import (
    CellRenderPlan,
    DailyExcelRenderPlan,
    RenderBorderRole,
    RenderFillRole,
    RenderFontRole,
    RenderIssue,
    RenderLine,
    RenderLineRole,
    SessionCellBinding,
    build_daily_excel_render_plan,
)

from .render_writeback import (
    RenderWritebackError,
    RenderWritebackSummary,
    build_daily_write_plan,
    summarize_daily_write_plan,
)

from .native_excel import (
    NativeExcelWriteError,
    NativeStylePalette,
    NativeWriteReport,
    Win32ComExcelBackend,
    apply_write_plan_to_copy,
    excel_rgb,
)

from .source_contract import (
    AUTHORITATIVE_SHEETS,
    SOURCE_RULES,
    SheetAuthority,
    SheetSourceRule,
    get_source_rule,
    imported_sheets,
    is_authoritative,
)

__all__ = [
    "AUTHORITATIVE_SHEETS",
    "AuditIssue",
    "SOURCE_RULES",
    "SheetAuthority",
    "SheetSourceRule",
    "SourceContractError",
    "WorkbookAudit",
    "WorkbookSettings",
    "WorkbookSnapshot",
    "validate_write_plan",
    "dry_run_writeback",
    "build_write_plan",
    "WritebackSafetyError",
    "WritePlan",
    "WriteIntent",
    "DryRunReport",
    "CellPatch",
    "TextRunPatch",
    "RenderWritebackError",
    "RenderWritebackSummary",
    "build_daily_write_plan",
    "summarize_daily_write_plan",
    "NativeExcelWriteError",
    "NativeStylePalette",
    "NativeWriteReport",
    "Win32ComExcelBackend",
    "apply_write_plan_to_copy",
    "excel_rgb",
    "audit_workbook",
    "build_snapshot",
    "get_source_rule",
    "imported_sheets",
    "is_authoritative",
    "read_base_schedule",
    "read_patients",
    "read_settings",
    "MASTER_SCHEDULE_HEADERS",
    "THERAPIST_DAILY_GRID_RANGES",
    "THERAPIST_DAILY_HEADER_RANGES",
    "WRITE_ZONES",
    "CellRange",
    "LayoutAudit",
    "LayoutIssue",
    "LayoutSafetyError",
    "SheetPackageInfo",
    "WorkbookPackageProbe",
    "assert_cell_write_allowed",
    "audit_layout",
    "resolve_master_schedule_rows",
    "resolve_therapist_daily_cell",
    "CellRenderPlan",
    "DailyExcelRenderPlan",
    "RenderBorderRole",
    "RenderFillRole",
    "RenderFontRole",
    "RenderIssue",
    "RenderLine",
    "RenderLineRole",
    "SessionCellBinding",
    "build_daily_excel_render_plan",
]
